{
 "title": "slurm",
 "description": "Zestaw wykresów obrazujących aktualne zużycie zasobów w ramach klastra obliczeniowego SLURM na Politechnice Poznańskiej",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Aktualna zajętość klastra", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ilość zadań w kolejce",
   "type": "timeseries",
   "description": "Wykres pokazuje ilość zadań aktualnie wykonywanych (running_tasks), ilość zadań oczekujących na zasoby (pending_tasks) oraz\nilość zadań aktualnie kończących pracę (completing_tasks)",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"slurm\")\n  |> range(start: -24h)\n  |> filter(fn: (r) =>\n    r._measurement == \"slurm_queue_running\"\n  )\n  |> map(fn: (r) => ({ r with _field: \"\", _measurement: \"#running_tasks\" }))\n  |> keep(columns: [\"_time\", \"_value\", \"_field\", \"_measurement\"])"
    },
    {
     "query": "from(bucket: \"slurm\")\n  |> range(start: -24h)\n  |> filter(fn: (r) =>\n    r._measurement == \"slurm_queue_completing\"\n  )\n  |> map(fn: (r) => ({ r with _field: \"\", _measurement: \"#completing_tasks\" }))\n  |> keep(columns: [\"_time\", \"_value\", \"_field\", \"_measurement\"])"
    },
    {
     "query": "from(bucket: \"slurm\")\n  |> range(start: -24h)\n  |> filter(fn: (r) =>\n    r._measurement == \"slurm_queue_pending\"\n  )\n  |> map(fn: (r) => ({ r with _field: \"\", _measurement: \"#pending_tasks\" }))\n  |> keep(columns: [\"_time\", \"_value\", \"_field\", \"_measurement\"])"
    }
   ]
  },
  {
   "title": "Stan klastra",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: \"slurm\")\n  |> range(start: -24h)\n  |> filter(fn: (r) =>\n    r._measurement == \"slurm_nodes_idle\"\n  )\n  |> map(fn: (r) => ({ r with _field: \"\", _measurement: \"idle_nodes\" }))\n  |> keep(columns: [\"_time\", \"_value\", \"_field\", \"_measurement\"])"
    },
    {
     "query": "from(bucket: \"slurm\")\n  |> range(start: -24h)\n  |> filter(fn: (r) =>\n    r._measurement == \"slurm_nodes_resv\"\n  )\n  |> map(fn: (r) => ({ r with _field: \"\", _measurement: \"reserved_nodes\" }))\n  |> keep(columns: [\"_time\", \"_value\", \"_field\", \"_measurement\"])"
    },
    {
     "query": "from(bucket: \"slurm\")\n  |> range(start: -24h)\n  |> filter(fn: (r) =>\n    r._measurement == \"slurm_nodes_alloc\"\n  )\n  |> map(fn: (r) => ({ r with _field: \"\", _measurement: \"allocated_nodes\" }))\n  |> keep(columns: [\"_time\", \"_value\", \"_field\", \"_measurement\"])"
    }
   ]
  },
  {
   "title": "Ilość zaalokowanej pamięci",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"slurm\")\n  |> range(start: -24h)\n  |> filter(fn: (r) =>\n    r._measurement == \"slurm_node_mem_alloc\"\n  )\n  |> map(fn: (r) => ({ r with _field: \"node_mem_alloc\", _measurement: \"node_mem_alloc\" }))\n  |> keep(columns: [\"_time\", \"_value\", \"_field\", \"_measurement\", \"node\"])"
    }
   ]
  },
  {
   "title": "Zajętość rdzeni CPU",
   "type": "timeseries",
   "description": "Ilość zajętych rdzeni vs ilość żądanych rdzeni",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"slurm\")\n  |> range(start: -24h)\n  |> filter(fn: (r) =>\n    r._measurement == \"slurm_node_cpu_alloc\"\n  )\n  |> map(fn: (r) => ({ r with _field: \"\", _measurement: \"node_cpu_alloc\" }))\n  |> keep(columns: [\"_time\", \"_value\", \"_field\", \"_measurement\", \"node\"])"
    },
    {
     "query": "from(bucket: \"slurm\")\n  |> range(start: -24h)\n  |> filter(fn: (r) =>\n   r._measurement == \"slurm_node_cpu_idle\"\n  )\n  |> map(fn: (r) => ({ r with _field: \"\", _measurement: \"node_cpu_idle\" }))\n  |> keep(columns: [\"_time\", \"_value\", \"_field\", \"_measurement\", \"node\"])"
    }
   ]
  }
 ]
}